import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/global.scss";
import { StoreProvider } from "./providers/StoreProvider";
import { Container } from "@/shared/ui/Container/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const inter = Inter({
  subsets: ["cyrillic"],
  weight: ["500"]
});

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <Container>
      <html lang="en" className={inter.className}>
        <StoreProvider>
          <body>{children}</body>
        </StoreProvider>
      </html>
    </Container>
  );
};

export default RootLayout;
