import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const inter = Inter({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600"]
});

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
